---
- hosts: localhost
  vars_files:
    - credentials.yml
  vars:
    tags: '{"Name":"sample_instance"}'
  tasks:
    - name: Spin up instance
      ec2:
        aws_secret_key: "{{ aws_secret_key }}"
        aws_access_key: "{{ aws_access_key }}"
        region: "us-east-1"
        image: "ami-2051294a"
        instance_type: "t2.micro"
        instance_tags: "{{ tags }}"
        count_tag: "{{ tags }}"
        exact_count: 1
        assign_public_ip: yes
        wait: yes
        vpc_subnet_id: subnet-86167fde        
      register: created_instances

    - name: Add host to the group
      add_host:
        groupname=ec2hosts
        instance_tags="{{item.tags}}"
        ansible_user=ec2-user
        ansible_ssh_host=localhost
        ansible_ssh_port=22
        ansible_ssh_private_key_file=".keys/sharedKey.pem"
      with_items: created_instances.instances
    
    - name: Wait for SSH to come up
      local_action:
        wait_for host="{{item.public_dns}}"
        port=22
        delay=10
        timeout=240
        state=started
      with_items: created_instances.instances

- hosts: ec2hosts
  tasks:
    - name: Install package
      yum: name=wget state=present