---
- hosts: controllerBox
  vars_files:
    - credentials.yml
  vars:
    tags: '{"Name":"sample_instance"}'
  tasks:
    - name: Create Security group
      ec2_group:
        aws_secret_key: "{{ aws_secret_key }}"
        aws_access_key: "{{ aws_access_key }}"
        name: "sample"
        description: "security rules for sample_instance"
        vpc_id: "vpc-f720e893"
        region: "us-east-1"

    - name: Spin up instance
      ec2:
        aws_secret_key: "{{ aws_secret_key }}"
        aws_access_key: "{{ aws_access_key }}"
        region: "us-east-1"
        image: "ami-2051294a"
        instance_type: "t2.micro"
        instance_tags: "{{ tags }}"
        count_tag: "{{ tags }}"
        exact_count: 1
        assign_public_ip: yes
        group: sample
        wait: yes
        key_name: "sharedKey"
        vpc_subnet_id: subnet-86167fde        
      register: created_instances

    - name: Add host to the group
      add_host:
        hostname="{{ item.public_dns_name }}"
        groupname="webServers"
        instance_tags="{{ item.tags }} "
        ansible_user=ec2-user
        ansible_ssh_host="{{item.public_dns_name}}"
        ansible_ssh_port=22
        ansible_ssh_private_key_file=".keys/sharedKey.pem"
      with_items: created_instances.tagged_instances
    
    - name: Wait for SSH to come up
      wait_for:
        host="{{ item.public_dns_name }}"
        port=22
        state=started
      with_items: created_instances.tagged_instances

- hosts: webServers
  become: yes
  roles:
    - webServer
